### ISSUE TITLE
Cannot create new record with valid attributes

### ISSUE THREAD

**Issue by ingeniousgenius** [graphiti-api/graphiti_errors#10]
I'm running the latest versions of the Graphiti toolkit on Rails 6.2 and I'm unable to create a new record with my API, given valid attributes. An error is thrown when there are no validation errors like so:

```bash
#<NoMethodError: undefined method `[]' for nil:NilClass>
```

which points to like 42 in this file https://github.com/graphiti-api/graphiti_errors/blob/master/lib/graphiti_errors/validation/serializer.rb

```ruby
          details = if Rails::VERSION::MAJOR >= 5
            object.errors.details.find { |k, v| k == attribute }[1]
          end
```

When there are validation errors, the `NoMethodError` is not thrown. Only when the record is valid.

Request:

```json
POST localhost:3000/api/v1/accounts

{
	"data": {
		"type": "accounts",
		"attributes": {
			"name": "Savings Account",
			"account_type": "savings",
			"currency": "eur"
		}
	}
}
```

Response:

```json
"meta": {
        "__details__": {
          "exception": "#<NoMethodError: undefined method `[]' for nil:NilClass>",
          "traces": {
            "Application Trace": [
              {
                "exception_object_id": 70175924115520,
                "id": 24,
                "trace": "app/controllers/accounts_controller.rb:20:in `create'"
              }
            ],
            "Framework Trace": [
              {
                "exception_object_id": 70175924115520,
                "id": 0,
                "trace": "graphiti_errors (1.1.1) lib/graphiti_errors/validation/serializer.rb:42:in `block in each_error'"
              },
              //... irrelevant back trace
           ]
    }

```

**Comment by ingeniousgenius** [comment]
It's worth adding the resource and the model too.

account_resource.rb
```ruby
class AccountResource < ApplicationResource
  attribute :user_id, :integer, only: [:filterable]
  attribute :account_type, :string
  attribute :currency, :string
  attribute :name, :string
end
```

accounts_controller.rb
```ruby
class AccountsController < ApplicationController
  before_action :authenticate

  def index
    accounts = AccountResource.all(params)
    respond_with(accounts)
  end

  def show
    account = AccountResource.find(params)
    respond_with(account)
  end

  def create
    account = AccountResource.build(params)

    if account.save
      render jsonapi: account, status: 201
    else
      render jsonapi_errors: account
    end
  end

  def update
    account = AccountResource.find(params)

    if account.update_attributes
      render jsonapi: account
    else
      render jsonapi_errors: account
    end
  end

  def destroy
    account = AccountResource.find(params)

    if account.destroy
      render jsonapi: { meta: {} }, status: 200
    else
      render jsonapi_errors: account
    end
  end
end
```

It's worth noting that disabling validations completely seems to solve the issue, however, that's not really viable.

**Comment by ingeniousgenius** [comment]
Okay, one more thing I noticed was that I was using a custom validator class and when these validations with the custom validation classes were removed, the code worked.

The validation classes are:

```ruby
class CurrencyValidator < ActiveModel::EachValidator
  CURRENCIES = %w[
    USD
    EUR
    CAD
    GBP
  ].freeze

  def validate_each(object, attribute, value)
    return unless value.present?
    return if value.present? && CURRENCIES.include?(value)

    object.errors[attribute] << (options[:message] || "must be one of #{CURRENCIES}")
  end
end
```

```ruby
class EnumValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    enum = options
    keys = enum.keys

    return unless value.present?

    record.errors.add attribute, "must be one of #{keys}" unless keys.include? value
  end
end
```

**Comment by yasirazgar** [comment]
@jesster2k10 probably this is will be fixed by https://github.com/graphiti-api/graphiti_errors/pull/12, you can try this branch in my [fork](https://github.com/yasirazgar/graphiti_errors/tree/11-add_missing_super)

**Comment by mkamensky** [comment]
As far as I understand, the reason is that having an attribute in `errors.messages` need not imply that it also exists in `errors.details`. In fact, `ActiveModel::Errors` initializes entries in `errors.messages` when they are reference:

https://github.com/rails/rails/blob/34991a6ae2fc68347c01ea7382fa89004159e019/activemodel/lib/active_model/errors.rb#L554

and a corresponding key need not exist in `details`. A solution is to replace `[1]` with `.try(:[], 1)`
